### ISSUE TITLE
BootStrap 에서 기능 별 페이지 연결하기

### ISSUE THREAD

**Issue by aicompose** [GoOnThat/GoOnThat-Backend#16]
## Description
HTML 을 개발하였을 경우 사용하는 이슈 템플릿입니다.

---

## TODO

---
- [ ] 각 페이지 별 넘어가게 설정하기
- [ ] index.html 이 뿌리 나머지 본인들이 설정 한 페이지 기능 외의 기능들 제거
- [ ] 세부적인 페이지 만들기

---

## ETC
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.

---

* 변경된 이미지를 넣어주세요.
