### ISSUE TITLE
BootStrap template 백앤드 공간으로 넘기기

### ISSUE THREAD

**Issue by aicompose** [GoOnThat/GoOnThat-Backend#5]
## Description
HTML 을 개발하였을 경우 사용하는 이슈 템플릿입니다.

---

## TODO

---
- [ ]  header, footer 등 기초 고정값 확인
- [ ]  js 파일, 이미지 파일 static 영역으로 넘기기
- [ ]  효정님의 html mapping과 연결해두기

---

## ETC
* 부트스트렙 html 파일 연동여부 미지수

---

* 변경된 이미지를 넣어주세요.
