### ISSUE TITLE
게시판 검색기능 구현

### ISSUE THREAD

**Issue by devJaem** [GoOnThat/GoOnThat-Backend#86]
## Description
Service 를 개발하였을 경우 사용하는 이슈 템플릿입니다.   
### 아래 항목 중 해당하는 Service의 패키지를 선택해주세요.
- [ ] Application
- [ ] Domain
---
## 주요 서비스 로직
1. Page<> 를 이용한 페이징

---

## 주요 메서드
해당 클래스의 주요 메서드를 입력합니다.   
1. Page<FreeBoardListDTO> getSearchPosts
3.  public String list( @RequestParam(required = false) String searchKeyword,
                        @RequestParam(required = false) String key,
                        @PageableDefault(page = 0, sort = "boardNo", direction = Sort.Direction.DESC) Pageable pageable
            , Model model)

---

## TODO
- [ ]  할일 목록을 작성한다.
- [ ]  할일 목록을 작성한다.
- [ ]  할일 목록을 작성한다.

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.

**Additional context**
