### ISSUE TITLE
[권한 별 버튼 활성화] 글, 댓글에 관한 버튼 활성화 처리

### ISSUE THREAD

**Issue by aicompose** [GoOnThat/GoOnThat-Backend#96]
## Description
특정 클래스의 메서드를 수정할 경우 작성하는 이슈 템플릿입니다.

### 아래 항목 중 해당하는 메서드를 수정을 선택해주세요.
- [x] Create
- [x] Update
- [x] Delete
---

## 주요 메서드 로직
새로 업데이트되는 메서드 로직을 작성해주세요.  

예시)

* th:if="${user != null && user.nickname == comment.commentWriter}"

---

## 메서드
해당 클래스의 주요 메서드를 입력합니다.   
예시)

~~~
th:if="${user != null && user.nickname == comment.commentWriter}"
~~~

---

## TODO
- [ ]  할일 목록을 작성한다.
- [ ]  할일 목록을 작성한다.
- [ ]  할일 목록을 작성한다.

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
